name: build

on:
  #push:
  #  branches: [ "master" ]
  workflow_dispatch:

jobs:
  flatter:
    name: Flatter
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/freedesktop/x86_64:22.08
      options: --privileged
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Build
      id: flatpak
      uses: andyholmes/actions/flatter@main
      with:
        files: |
          com.anydesk.Anydesk.json
        upload-pages-artifact: true
        upload-pages-includes: |
          default.css
          index.html

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: flatter
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
