name: build

on:
  #push:
  #  branches: [ "master" ]
  workflow_dispatch:

jobs:
  flatter:
    name: Flatter
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/freedesktop/x86_64:22.08
      options: --privileged
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Build
      id: flatpak
      uses: andyholmes/flatter@main
      with:
        files: |
          com.anydesk.Anydesk.json
    - name: Deploy Repository
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        folder: ${{ steps.flatpak.outputs.repository }}
        target-folder: repo
